[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "anticaptrad-client"
version = "0.1.0"
description = "Anticaptrad API client"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["act_client"]
